global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: messenger
    environment: local

scrape_configs:
  - job_name: auth-service
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: message-service
    static_configs:
      - targets: [ 'message-service:8082' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: file-service
    static_configs:
      - targets: [ 'file-service:8083' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: chat-service
    static_configs:
      - targets: [ 'chat-service:8084' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: account-service
    static_configs:
      - targets: [ 'account-service:8085' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: realtime-gateway
    static_configs:
      - targets: [ 'realtime-gateway:8086' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: fulltext-search-service
    static_configs:
      - targets: [ 'fulltext-search-service:8087' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: mail-service
    static_configs:
      - targets: [ 'mail-service:8088' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: analytic-service
    static_configs:
      - targets: [ 'analytic-service:8090' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: api-gateway
    static_configs:
      - targets: [ 'api-gateway:8080' ]
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
  - job_name: postgres
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
    scrape_interval: 15s
  - job_name: redis
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

