spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8083

grpc:
  server:
    port: 9091

minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  endpoint: ${MINIO_ENDPOINT}
  file-max-size-bytes: 104857600 # 100 MB
  default-presigned-url-expiration: 24h
  buckets:
    message_image:
      presigned-url-expiration: 3h
    message_video:
      presigned-url-expiration: 1h
    message_audio:
      presigned-url-expiration: 5h
    message_document:
      presigned-url-expiration: 6h
    account_icon:
      presigned-url-expiration: 12h
    chat_icon:
      presigned-url-expiration: 12h

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health
