CREATE TABLE message_statuses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id BIGINT                                  NOT NULL,
    user_id    UUID,
    status     VARCHAR(255)                            NOT NULL,
    read_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_message_statuses PRIMARY KEY (id)
);

CREATE TABLE messages
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id             UUID                                    NOT NULL,
    from_user_id        UUID                                    NOT NULL,
    content             TEXT,
    type                VARCHAR(255)                            NOT NULL,
    bucket_name         VARCHAR(255),
    file_url            VARCHAR(255),
    file_name           VARCHAR(255),
    file_size           BIGINT,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    deleted             BOOLEAN                                 NOT NULL,
    deleted_at          TIMESTAMP WITHOUT TIME ZONE,
    is_edited           BOOLEAN                                 NOT NULL,
    reply_to_message_id BIGINT,
    CONSTRAINT pk_messages PRIMARY KEY (id)
);

ALTER TABLE message_statuses
    ADD CONSTRAINT uc_72b53c0133d4ddd4d89694bde UNIQUE (message_id, user_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_REPLY_TO_MESSAGE FOREIGN KEY (reply_to_message_id) REFERENCES messages (id);

ALTER TABLE message_statuses
    ADD CONSTRAINT FK_MESSAGE_STATUSES_ON_MESSAGE FOREIGN KEY (message_id) REFERENCES messages (id);